os: Visual Studio 2017
platform: x64
clone_folder: C:\rpcs3
clone_depth: 3

configuration:
  - Release

before_build:
  - ps: $env:Date="$(git show -s --date=short --format='%ad')"
  - git clone https://github.com/llvm-mirror/llvm
  - cd llvm\tools
  - git clone https://github.com/llvm-mirror/polly
  - cd ..\..\
  - mkdir llvm_build
  - cd llvm_build
  - cmake -G "Visual Studio 15 Win64" ../llvm -DLLVM_TARGETS_TO_BUILD="X86" -DCMAKE_BUILD_TYPE=Release -DLLVM_PARALLEL_COMPILE_JOBS=2 -DLLVM_PARALLEL_LINK_JOBS=2 -Thost=x64
  - dir
build_script:
  - cmake --build . --config Release -- /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
after_build:
  - cd ..\
  - mkdir build
  - cd build
  - mkdir llvm
  - cd llvm
  - xcopy "..\..\llvm\cmake" ".\" /E
  - xcopy "..\..\llvm\include" ".\" /E
  - cd ..\
  - mkdir llvm_build
  - cd llvm_build
  - xcopy "..\..\llvm_build\Release" ".\" /E
  - xcopy  "..\..\llvm_build\include" ".\" /E
  - xcopy  "..\..\llvm_build\lib" ".\" /E
  - cd ..\
  - 7z a -r "llvmlibs.7z" *
  - mkdir C:\rpcs3\bin
  - move .\llvmlibs.7z C:\rpcs3\bin\
artifacts:
 - path: bin
   name: 'llvmlibs.7z'
   type: File
