os: Visual Studio 2017
platform: x64
clone_folder: C:\dabuild
clone_depth: 3

before_build:
  - ps: $env:Date="$(git show -s --date=short --format='%ad')"
  - appveyor DownloadFile http://releases.llvm.org/6.0.0/llvm-6.0.0.src.tar.xz
  - 7z x llvm-6.0.0.src.tar.xz
  - 7z x llvm-6.0.0.src.tar
  - move llvm-6.0.0.src llvm
  - mkdir llvm_build
  - cd llvm_build
   - cmake -G "Visual Studio 15 Win64" ../llvm -DLLVM_TARGETS_TO_BUILD="X86" -DLLVM_DEFAULT_TARGET_TRIPLE:STRING=x86_64-pc-win64 -DLLVM_HOST_TRIPLE:STRING=x86_64-pc-win64 -DCMAKE_BUILD_TYPE=Release -Thost=x64 -DLLVM_BUILD_RUNTIME=OFF  -DLLVM_BUILD_TOOLS=OFF  -DLLVM_INCLUDE_DOCS=OFF -DLLVM_INCLUDE_EXAMPLES=OFF -DCMAKE_SYSTEM_VERSION=6.1 -DCMAKE_VS_WINDOWS_TARGET_PLATFORM_VERSION=8.1r
  - cmake --build . --config Release -- /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
after_build:
  - cd ..\
  - mkdir build
  - cd build
  - mkdir llvm
  - cd llvm
  - xcopy "..\llvm\cmake" ".\" /E
  - xcopy "..\llvm\include" ".\" /E
  - cd ..\
  - mkdir llvm_build
  - cd llvm_build
  - xcopy "..\llvm_build\Release" ".\" /E
  - xcopy  "..\llvm_build\include" ".\" /E
  - xcopy  "..\llvm_build\lib" ".\" /E
  - cd ..\
  - 7z a -r "llvmlibs.7z" *
  - move .\llvmlibs.7z ..\bin\
artifacts:
 - path: bin
   name: 'llvmlibs.7z'
type: File
